### ISSUE TITLE
[Comment] Yoneda lemma

### ISSUE THREAD

**Issue by giuliohome** [hablapps/LensStateIsYourFather#3]
Quick question:
Have you thought about re-interpreting the relationship between lens and state monad as a consequence derived from the Yoneda lemma?
As Bartosz Milewski [puts](https://bartoszmilewski.com/2014/01/14/functors-are-containers/) it: 
"On the one hand you have a polymorphic function, on the other hand a polymorphic data structure, and they encode the same data."
Also Edward Kmett makes a case for generalized profunctor lenses whenever we have a monoidal category and Phil Freeman [explain](http://blog.functorial.com/posts/2016-08-08-Comonad-And-Day-Convolution.html) that "it turns out that many standard comonad transformers are already isomorphic to Day f for some f, so we can use these optics to easily operate inside comonad transformer stacks."

Oh and that's [From Lenses to Yoneda Embedding](https://bartoszmilewski.com/2015/07/13/from-lenses-to-yoneda-embedding/):
"Let’s for a moment concentrate on the monomorphic version of the lens" ... "Substitute Store a for f and you see that a lens is nothing but a coalgebra for this functor. This is not saying much — we have just given a mathematical name to a programming construct, no big deal. Except that Store a is more than a functor — it’s also a comonad." ...

I immediately recognised a classical deja vu!

**Comment by neutropolis** [comment]
@giuliohome I don't know why, but I'm not receiving notifications from GitHub, sorry for the delay! I'm quite busy these days with some deadlines but I promise to come back to this re-interpretation next week. It seems promising! :smile:

**Comment by neutropolis** [comment]
Ouch! I forgot about this issue... First of all, many thanks for taking your time establishing these connections and I'd like to apologize for the delay (again). I agree that Yoneda is quite useful to experiment with optics, as Bartosz Milewski (and others) have perfectly shown. Particularly, I find it essential to relate concrete optics with other representations where natural transformations are involved, such as *van Laarhoven* or *Profunctor*. Beyond those representations, I've been trying to do an analogous exercise for the state monad morphism representation `forall x. state a x -> state s x`, where the state monad is involved.

However I can't see how to relate concrete lenses with the representation that we proposed: `MonadState[A, state s]`. This is the same as: `(1 -> S -> S * A) * (A -> S -> S * 1)`. If I have understood correctly, you want to apply the Yoneda lemma to get: `S -> (A, A -> S)` (Store comonad coalgebra), but I'm not sure about how to do so in this scenario. Could you provide more details? Thank you @giuliohome!

**Comment by giuliohome** [comment]
I see what you mean, yes, you're right, what you proposed seems more related to Entangled State Monads as far as I can understand, so I would suggest this [Extended abstract pdf](http://groups.inf.ed.ac.uk/bx/monad.pdf) and especially the [Notions of Bidirectional Computation and Entangled State Monads](http://groups.inf.ed.ac.uk/bx/bx-effects-tr.pdf) (e.g. Lemma 11 pag 8, Theorem 46 pag 35, Comparison with symmetric lenses in Appendice A) for more details...

**Comment by neutropolis** [comment]
Those references are really nice. Indeed, we have a [draft paper](https://github.com/hablapps/LensAlgebra) that heavily relies on them, where we formalize the ideas on this post.
